//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_s_App.ReservationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.projectXml.com/reservation", ConfigurationName="ReservationServiceReference.ReservationPort")]
    public interface ReservationPort {
        
        // CODEGEN: Generating message contract since the operation confirmReservation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.ReservationServiceReference.confirmReservationResponse1 confirmReservation(Agent_s_App.ReservationServiceReference.confirmReservationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.confirmReservationResponse1> confirmReservationAsync(Agent_s_App.ReservationServiceReference.confirmReservationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getReservationsByUnit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.ReservationServiceReference.getReservationsByUnitResponse1 getReservationsByUnit(Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.getReservationsByUnitResponse1> getReservationsByUnitAsync(Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest1 request);
        
        // CODEGEN: Generating message contract since the operation confirmComment is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.ReservationServiceReference.confirmCommentResponse1 confirmComment(Agent_s_App.ReservationServiceReference.confirmCommentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.confirmCommentResponse1> confirmCommentAsync(Agent_s_App.ReservationServiceReference.confirmCommentRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getReservation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.ReservationServiceReference.getReservationResponse1 getReservation(Agent_s_App.ReservationServiceReference.getReservationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.getReservationResponse1> getReservationAsync(Agent_s_App.ReservationServiceReference.getReservationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addReservation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.ReservationServiceReference.addReservationResponse1 addReservation(Agent_s_App.ReservationServiceReference.addReservationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.addReservationResponse1> addReservationAsync(Agent_s_App.ReservationServiceReference.addReservationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation deleteComment is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.ReservationServiceReference.deleteCommentResponse1 deleteComment(Agent_s_App.ReservationServiceReference.deleteCommentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.deleteCommentResponse1> deleteCommentAsync(Agent_s_App.ReservationServiceReference.deleteCommentRequest1 request);
        
        // CODEGEN: Generating message contract since the operation updateReservation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.ReservationServiceReference.updateReservationResponse1 updateReservation(Agent_s_App.ReservationServiceReference.updateReservationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.updateReservationResponse1> updateReservationAsync(Agent_s_App.ReservationServiceReference.updateReservationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation deleteReservation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.ReservationServiceReference.deleteReservationResponse1 deleteReservation(Agent_s_App.ReservationServiceReference.deleteReservationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.deleteReservationResponse1> deleteReservationAsync(Agent_s_App.ReservationServiceReference.deleteReservationRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class confirmReservationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long id_reservationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id_reservation {
            get {
                return this.id_reservationField;
            }
            set {
                this.id_reservationField = value;
                this.RaisePropertyChanged("id_reservation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/reservation")]
    public partial class commentRate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool approvedCommentField;
        
        private string contentOfCommentField;
        
        private System.DateTime commentDateField;
        
        private int ocenaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool approvedComment {
            get {
                return this.approvedCommentField;
            }
            set {
                this.approvedCommentField = value;
                this.RaisePropertyChanged("approvedComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string contentOfComment {
            get {
                return this.contentOfCommentField;
            }
            set {
                this.contentOfCommentField = value;
                this.RaisePropertyChanged("contentOfComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime commentDate {
            get {
                return this.commentDateField;
            }
            set {
                this.commentDateField = value;
                this.RaisePropertyChanged("commentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ocena {
            get {
                return this.ocenaField;
            }
            set {
                this.ocenaField = value;
                this.RaisePropertyChanged("ocena");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/reservation")]
    public partial class accommodation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string nameField;
        
        private string categoryField;
        
        private address addressField;
        
        private accommodationType accommodationTypeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public accommodationType AccommodationType {
            get {
                return this.accommodationTypeField;
            }
            set {
                this.accommodationTypeField = value;
                this.RaisePropertyChanged("AccommodationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/reservation")]
    public partial class address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string cityField;
        
        private int postal_codeField;
        
        private string streetField;
        
        private string numberField;
        
        private string apartment_numberField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                this.postal_codeField = value;
                this.RaisePropertyChanged("Postal_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Apartment_number {
            get {
                return this.apartment_numberField;
            }
            set {
                this.apartment_numberField = value;
                this.RaisePropertyChanged("Apartment_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/reservation")]
    public enum accommodationType {
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        MOTEL,
        
        /// <remarks/>
        BED_AND_BREAKFAST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/reservation")]
    public partial class accommodationUnitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/reservation")]
    public partial class accommodationUnit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int floorField;
        
        private string numberField;
        
        private int numberOfBedsField;
        
        private double defaultPriceField;
        
        private accommodationUnitType accommodationUnitTypeField;
        
        private long idField;
        
        private accommodation accommodationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
                this.RaisePropertyChanged("Floor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NumberOfBeds {
            get {
                return this.numberOfBedsField;
            }
            set {
                this.numberOfBedsField = value;
                this.RaisePropertyChanged("NumberOfBeds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double DefaultPrice {
            get {
                return this.defaultPriceField;
            }
            set {
                this.defaultPriceField = value;
                this.RaisePropertyChanged("DefaultPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public accommodationUnitType AccommodationUnitType {
            get {
                return this.accommodationUnitTypeField;
            }
            set {
                this.accommodationUnitTypeField = value;
                this.RaisePropertyChanged("AccommodationUnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public accommodation Accommodation {
            get {
                return this.accommodationField;
            }
            set {
                this.accommodationField = value;
                this.RaisePropertyChanged("Accommodation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/reservation")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string lastnameField;
        
        private string emailField;
        
        private string usernameField;
        
        private string passwordField;
        
        private long idField;
        
        private bool enabledField;
        
        private bool deletedField;
        
        private string roleField;
        
        private address addressField;
        
        private long bussines_registration_numberField;
        
        private bool blockedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("Lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long Bussines_registration_number {
            get {
                return this.bussines_registration_numberField;
            }
            set {
                this.bussines_registration_numberField = value;
                this.RaisePropertyChanged("Bussines_registration_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
                this.RaisePropertyChanged("Blocked");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/reservation")]
    public partial class reservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool confirmedField;
        
        private bool agentConfirmedField;
        
        private user guestField;
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        private accommodationUnit accommodationUnitField;
        
        private commentRate commentRateField;
        
        private double priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool confirmed {
            get {
                return this.confirmedField;
            }
            set {
                this.confirmedField = value;
                this.RaisePropertyChanged("confirmed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool agentConfirmed {
            get {
                return this.agentConfirmedField;
            }
            set {
                this.agentConfirmedField = value;
                this.RaisePropertyChanged("agentConfirmed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public user guest {
            get {
                return this.guestField;
            }
            set {
                this.guestField = value;
                this.RaisePropertyChanged("guest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime fromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("fromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime toDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("toDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public accommodationUnit accommodationUnit {
            get {
                return this.accommodationUnitField;
            }
            set {
                this.accommodationUnitField = value;
                this.RaisePropertyChanged("accommodationUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public commentRate commentRate {
            get {
                return this.commentRateField;
            }
            set {
                this.commentRateField = value;
                this.RaisePropertyChanged("commentRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class confirmReservationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmReservationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.confirmReservationRequest confirmReservationRequest;
        
        public confirmReservationRequest1() {
        }
        
        public confirmReservationRequest1(Agent_s_App.ReservationServiceReference.confirmReservationRequest confirmReservationRequest) {
            this.confirmReservationRequest = confirmReservationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmReservationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.confirmReservationResponse confirmReservationResponse;
        
        public confirmReservationResponse1() {
        }
        
        public confirmReservationResponse1(Agent_s_App.ReservationServiceReference.confirmReservationResponse confirmReservationResponse) {
            this.confirmReservationResponse = confirmReservationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class getReservationsByUnitRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long unitIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long unitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("unitId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class getReservationsByUnitResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long unitIdField;
        
        private reservation[] reservationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long unitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("unitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reservations", Order=1)]
        public reservation[] reservations {
            get {
                return this.reservationsField;
            }
            set {
                this.reservationsField = value;
                this.RaisePropertyChanged("reservations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReservationsByUnitRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest getReservationsByUnitRequest;
        
        public getReservationsByUnitRequest1() {
        }
        
        public getReservationsByUnitRequest1(Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest getReservationsByUnitRequest) {
            this.getReservationsByUnitRequest = getReservationsByUnitRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReservationsByUnitResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.getReservationsByUnitResponse getReservationsByUnitResponse;
        
        public getReservationsByUnitResponse1() {
        }
        
        public getReservationsByUnitResponse1(Agent_s_App.ReservationServiceReference.getReservationsByUnitResponse getReservationsByUnitResponse) {
            this.getReservationsByUnitResponse = getReservationsByUnitResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class confirmCommentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long id_reservationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id_reservation {
            get {
                return this.id_reservationField;
            }
            set {
                this.id_reservationField = value;
                this.RaisePropertyChanged("id_reservation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class confirmCommentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmCommentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.confirmCommentRequest confirmCommentRequest;
        
        public confirmCommentRequest1() {
        }
        
        public confirmCommentRequest1(Agent_s_App.ReservationServiceReference.confirmCommentRequest confirmCommentRequest) {
            this.confirmCommentRequest = confirmCommentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmCommentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.confirmCommentResponse confirmCommentResponse;
        
        public confirmCommentResponse1() {
        }
        
        public confirmCommentResponse1(Agent_s_App.ReservationServiceReference.confirmCommentResponse confirmCommentResponse) {
            this.confirmCommentResponse = confirmCommentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class getReservationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class getReservationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private reservation reservationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public reservation reservation {
            get {
                return this.reservationField;
            }
            set {
                this.reservationField = value;
                this.RaisePropertyChanged("reservation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReservationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.getReservationRequest getReservationRequest;
        
        public getReservationRequest1() {
        }
        
        public getReservationRequest1(Agent_s_App.ReservationServiceReference.getReservationRequest getReservationRequest) {
            this.getReservationRequest = getReservationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReservationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.getReservationResponse getReservationResponse;
        
        public getReservationResponse1() {
        }
        
        public getReservationResponse1(Agent_s_App.ReservationServiceReference.getReservationResponse getReservationResponse) {
            this.getReservationResponse = getReservationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class addReservationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private reservation reservationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public reservation reservation {
            get {
                return this.reservationField;
            }
            set {
                this.reservationField = value;
                this.RaisePropertyChanged("reservation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class addReservationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addReservationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.addReservationRequest addReservationRequest;
        
        public addReservationRequest1() {
        }
        
        public addReservationRequest1(Agent_s_App.ReservationServiceReference.addReservationRequest addReservationRequest) {
            this.addReservationRequest = addReservationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addReservationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.addReservationResponse addReservationResponse;
        
        public addReservationResponse1() {
        }
        
        public addReservationResponse1(Agent_s_App.ReservationServiceReference.addReservationResponse addReservationResponse) {
            this.addReservationResponse = addReservationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class deleteCommentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long id_reservationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id_reservation {
            get {
                return this.id_reservationField;
            }
            set {
                this.id_reservationField = value;
                this.RaisePropertyChanged("id_reservation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class deleteCommentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteCommentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.deleteCommentRequest deleteCommentRequest;
        
        public deleteCommentRequest1() {
        }
        
        public deleteCommentRequest1(Agent_s_App.ReservationServiceReference.deleteCommentRequest deleteCommentRequest) {
            this.deleteCommentRequest = deleteCommentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteCommentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.deleteCommentResponse deleteCommentResponse;
        
        public deleteCommentResponse1() {
        }
        
        public deleteCommentResponse1(Agent_s_App.ReservationServiceReference.deleteCommentResponse deleteCommentResponse) {
            this.deleteCommentResponse = deleteCommentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class updateReservationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private reservation reservationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public reservation reservation {
            get {
                return this.reservationField;
            }
            set {
                this.reservationField = value;
                this.RaisePropertyChanged("reservation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class updateReservationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateReservationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.updateReservationRequest updateReservationRequest;
        
        public updateReservationRequest1() {
        }
        
        public updateReservationRequest1(Agent_s_App.ReservationServiceReference.updateReservationRequest updateReservationRequest) {
            this.updateReservationRequest = updateReservationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateReservationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.updateReservationResponse updateReservationResponse;
        
        public updateReservationResponse1() {
        }
        
        public updateReservationResponse1(Agent_s_App.ReservationServiceReference.updateReservationResponse updateReservationResponse) {
            this.updateReservationResponse = updateReservationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class deleteReservationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long reservation_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long reservation_id {
            get {
                return this.reservation_idField;
            }
            set {
                this.reservation_idField = value;
                this.RaisePropertyChanged("reservation_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/reservation")]
    public partial class deleteReservationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteReservationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.deleteReservationRequest deleteReservationRequest;
        
        public deleteReservationRequest1() {
        }
        
        public deleteReservationRequest1(Agent_s_App.ReservationServiceReference.deleteReservationRequest deleteReservationRequest) {
            this.deleteReservationRequest = deleteReservationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteReservationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/reservation", Order=0)]
        public Agent_s_App.ReservationServiceReference.deleteReservationResponse deleteReservationResponse;
        
        public deleteReservationResponse1() {
        }
        
        public deleteReservationResponse1(Agent_s_App.ReservationServiceReference.deleteReservationResponse deleteReservationResponse) {
            this.deleteReservationResponse = deleteReservationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReservationPortChannel : Agent_s_App.ReservationServiceReference.ReservationPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationPortClient : System.ServiceModel.ClientBase<Agent_s_App.ReservationServiceReference.ReservationPort>, Agent_s_App.ReservationServiceReference.ReservationPort {
        
        public ReservationPortClient() {
        }
        
        public ReservationPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.ReservationServiceReference.confirmReservationResponse1 Agent_s_App.ReservationServiceReference.ReservationPort.confirmReservation(Agent_s_App.ReservationServiceReference.confirmReservationRequest1 request) {
            return base.Channel.confirmReservation(request);
        }
        
        public Agent_s_App.ReservationServiceReference.confirmReservationResponse confirmReservation(Agent_s_App.ReservationServiceReference.confirmReservationRequest confirmReservationRequest) {
            Agent_s_App.ReservationServiceReference.confirmReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.confirmReservationRequest1();
            inValue.confirmReservationRequest = confirmReservationRequest;
            Agent_s_App.ReservationServiceReference.confirmReservationResponse1 retVal = ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).confirmReservation(inValue);
            return retVal.confirmReservationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.confirmReservationResponse1> Agent_s_App.ReservationServiceReference.ReservationPort.confirmReservationAsync(Agent_s_App.ReservationServiceReference.confirmReservationRequest1 request) {
            return base.Channel.confirmReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.confirmReservationResponse1> confirmReservationAsync(Agent_s_App.ReservationServiceReference.confirmReservationRequest confirmReservationRequest) {
            Agent_s_App.ReservationServiceReference.confirmReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.confirmReservationRequest1();
            inValue.confirmReservationRequest = confirmReservationRequest;
            return ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).confirmReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.ReservationServiceReference.getReservationsByUnitResponse1 Agent_s_App.ReservationServiceReference.ReservationPort.getReservationsByUnit(Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest1 request) {
            return base.Channel.getReservationsByUnit(request);
        }
        
        public Agent_s_App.ReservationServiceReference.getReservationsByUnitResponse getReservationsByUnit(Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest getReservationsByUnitRequest) {
            Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest1 inValue = new Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest1();
            inValue.getReservationsByUnitRequest = getReservationsByUnitRequest;
            Agent_s_App.ReservationServiceReference.getReservationsByUnitResponse1 retVal = ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).getReservationsByUnit(inValue);
            return retVal.getReservationsByUnitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.getReservationsByUnitResponse1> Agent_s_App.ReservationServiceReference.ReservationPort.getReservationsByUnitAsync(Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest1 request) {
            return base.Channel.getReservationsByUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.getReservationsByUnitResponse1> getReservationsByUnitAsync(Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest getReservationsByUnitRequest) {
            Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest1 inValue = new Agent_s_App.ReservationServiceReference.getReservationsByUnitRequest1();
            inValue.getReservationsByUnitRequest = getReservationsByUnitRequest;
            return ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).getReservationsByUnitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.ReservationServiceReference.confirmCommentResponse1 Agent_s_App.ReservationServiceReference.ReservationPort.confirmComment(Agent_s_App.ReservationServiceReference.confirmCommentRequest1 request) {
            return base.Channel.confirmComment(request);
        }
        
        public Agent_s_App.ReservationServiceReference.confirmCommentResponse confirmComment(Agent_s_App.ReservationServiceReference.confirmCommentRequest confirmCommentRequest) {
            Agent_s_App.ReservationServiceReference.confirmCommentRequest1 inValue = new Agent_s_App.ReservationServiceReference.confirmCommentRequest1();
            inValue.confirmCommentRequest = confirmCommentRequest;
            Agent_s_App.ReservationServiceReference.confirmCommentResponse1 retVal = ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).confirmComment(inValue);
            return retVal.confirmCommentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.confirmCommentResponse1> Agent_s_App.ReservationServiceReference.ReservationPort.confirmCommentAsync(Agent_s_App.ReservationServiceReference.confirmCommentRequest1 request) {
            return base.Channel.confirmCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.confirmCommentResponse1> confirmCommentAsync(Agent_s_App.ReservationServiceReference.confirmCommentRequest confirmCommentRequest) {
            Agent_s_App.ReservationServiceReference.confirmCommentRequest1 inValue = new Agent_s_App.ReservationServiceReference.confirmCommentRequest1();
            inValue.confirmCommentRequest = confirmCommentRequest;
            return ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).confirmCommentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.ReservationServiceReference.getReservationResponse1 Agent_s_App.ReservationServiceReference.ReservationPort.getReservation(Agent_s_App.ReservationServiceReference.getReservationRequest1 request) {
            return base.Channel.getReservation(request);
        }
        
        public Agent_s_App.ReservationServiceReference.getReservationResponse getReservation(Agent_s_App.ReservationServiceReference.getReservationRequest getReservationRequest) {
            Agent_s_App.ReservationServiceReference.getReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.getReservationRequest1();
            inValue.getReservationRequest = getReservationRequest;
            Agent_s_App.ReservationServiceReference.getReservationResponse1 retVal = ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).getReservation(inValue);
            return retVal.getReservationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.getReservationResponse1> Agent_s_App.ReservationServiceReference.ReservationPort.getReservationAsync(Agent_s_App.ReservationServiceReference.getReservationRequest1 request) {
            return base.Channel.getReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.getReservationResponse1> getReservationAsync(Agent_s_App.ReservationServiceReference.getReservationRequest getReservationRequest) {
            Agent_s_App.ReservationServiceReference.getReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.getReservationRequest1();
            inValue.getReservationRequest = getReservationRequest;
            return ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).getReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.ReservationServiceReference.addReservationResponse1 Agent_s_App.ReservationServiceReference.ReservationPort.addReservation(Agent_s_App.ReservationServiceReference.addReservationRequest1 request) {
            return base.Channel.addReservation(request);
        }
        
        public Agent_s_App.ReservationServiceReference.addReservationResponse addReservation(Agent_s_App.ReservationServiceReference.addReservationRequest addReservationRequest) {
            Agent_s_App.ReservationServiceReference.addReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.addReservationRequest1();
            inValue.addReservationRequest = addReservationRequest;
            Agent_s_App.ReservationServiceReference.addReservationResponse1 retVal = ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).addReservation(inValue);
            return retVal.addReservationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.addReservationResponse1> Agent_s_App.ReservationServiceReference.ReservationPort.addReservationAsync(Agent_s_App.ReservationServiceReference.addReservationRequest1 request) {
            return base.Channel.addReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.addReservationResponse1> addReservationAsync(Agent_s_App.ReservationServiceReference.addReservationRequest addReservationRequest) {
            Agent_s_App.ReservationServiceReference.addReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.addReservationRequest1();
            inValue.addReservationRequest = addReservationRequest;
            return ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).addReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.ReservationServiceReference.deleteCommentResponse1 Agent_s_App.ReservationServiceReference.ReservationPort.deleteComment(Agent_s_App.ReservationServiceReference.deleteCommentRequest1 request) {
            return base.Channel.deleteComment(request);
        }
        
        public Agent_s_App.ReservationServiceReference.deleteCommentResponse deleteComment(Agent_s_App.ReservationServiceReference.deleteCommentRequest deleteCommentRequest) {
            Agent_s_App.ReservationServiceReference.deleteCommentRequest1 inValue = new Agent_s_App.ReservationServiceReference.deleteCommentRequest1();
            inValue.deleteCommentRequest = deleteCommentRequest;
            Agent_s_App.ReservationServiceReference.deleteCommentResponse1 retVal = ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).deleteComment(inValue);
            return retVal.deleteCommentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.deleteCommentResponse1> Agent_s_App.ReservationServiceReference.ReservationPort.deleteCommentAsync(Agent_s_App.ReservationServiceReference.deleteCommentRequest1 request) {
            return base.Channel.deleteCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.deleteCommentResponse1> deleteCommentAsync(Agent_s_App.ReservationServiceReference.deleteCommentRequest deleteCommentRequest) {
            Agent_s_App.ReservationServiceReference.deleteCommentRequest1 inValue = new Agent_s_App.ReservationServiceReference.deleteCommentRequest1();
            inValue.deleteCommentRequest = deleteCommentRequest;
            return ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).deleteCommentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.ReservationServiceReference.updateReservationResponse1 Agent_s_App.ReservationServiceReference.ReservationPort.updateReservation(Agent_s_App.ReservationServiceReference.updateReservationRequest1 request) {
            return base.Channel.updateReservation(request);
        }
        
        public Agent_s_App.ReservationServiceReference.updateReservationResponse updateReservation(Agent_s_App.ReservationServiceReference.updateReservationRequest updateReservationRequest) {
            Agent_s_App.ReservationServiceReference.updateReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.updateReservationRequest1();
            inValue.updateReservationRequest = updateReservationRequest;
            Agent_s_App.ReservationServiceReference.updateReservationResponse1 retVal = ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).updateReservation(inValue);
            return retVal.updateReservationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.updateReservationResponse1> Agent_s_App.ReservationServiceReference.ReservationPort.updateReservationAsync(Agent_s_App.ReservationServiceReference.updateReservationRequest1 request) {
            return base.Channel.updateReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.updateReservationResponse1> updateReservationAsync(Agent_s_App.ReservationServiceReference.updateReservationRequest updateReservationRequest) {
            Agent_s_App.ReservationServiceReference.updateReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.updateReservationRequest1();
            inValue.updateReservationRequest = updateReservationRequest;
            return ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).updateReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.ReservationServiceReference.deleteReservationResponse1 Agent_s_App.ReservationServiceReference.ReservationPort.deleteReservation(Agent_s_App.ReservationServiceReference.deleteReservationRequest1 request) {
            return base.Channel.deleteReservation(request);
        }
        
        public Agent_s_App.ReservationServiceReference.deleteReservationResponse deleteReservation(Agent_s_App.ReservationServiceReference.deleteReservationRequest deleteReservationRequest) {
            Agent_s_App.ReservationServiceReference.deleteReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.deleteReservationRequest1();
            inValue.deleteReservationRequest = deleteReservationRequest;
            Agent_s_App.ReservationServiceReference.deleteReservationResponse1 retVal = ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).deleteReservation(inValue);
            return retVal.deleteReservationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.deleteReservationResponse1> Agent_s_App.ReservationServiceReference.ReservationPort.deleteReservationAsync(Agent_s_App.ReservationServiceReference.deleteReservationRequest1 request) {
            return base.Channel.deleteReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.ReservationServiceReference.deleteReservationResponse1> deleteReservationAsync(Agent_s_App.ReservationServiceReference.deleteReservationRequest deleteReservationRequest) {
            Agent_s_App.ReservationServiceReference.deleteReservationRequest1 inValue = new Agent_s_App.ReservationServiceReference.deleteReservationRequest1();
            inValue.deleteReservationRequest = deleteReservationRequest;
            return ((Agent_s_App.ReservationServiceReference.ReservationPort)(this)).deleteReservationAsync(inValue);
        }
    }
}
