//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_s_App.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.projectXml.com/mojuser", ConfigurationName="UserServiceReference.MojuserPort")]
    public interface MojuserPort {
        
        // CODEGEN: Generating message contract since the operation unblock is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.unblockResponse1 unblock(Agent_s_App.UserServiceReference.unblockRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.unblockResponse1> unblockAsync(Agent_s_App.UserServiceReference.unblockRequest1 request);
        
        // CODEGEN: Generating message contract since the operation login is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.loginResponse1 login(Agent_s_App.UserServiceReference.loginRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.loginResponse1> loginAsync(Agent_s_App.UserServiceReference.loginRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addAccommodationToUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.addAccommodationToUserResponse1 addAccommodationToUser(Agent_s_App.UserServiceReference.addAccommodationToUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.addAccommodationToUserResponse1> addAccommodationToUserAsync(Agent_s_App.UserServiceReference.addAccommodationToUserRequest1 request);
        
        // CODEGEN: Generating message contract since the operation activate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.activateResponse1 activate(Agent_s_App.UserServiceReference.activateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.activateResponse1> activateAsync(Agent_s_App.UserServiceReference.activateRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUserComments is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.getUserCommentsResponse getUserComments(Agent_s_App.UserServiceReference.getUserCommentsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.getUserCommentsResponse> getUserCommentsAsync(Agent_s_App.UserServiceReference.getUserCommentsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation block is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.blockResponse1 block(Agent_s_App.UserServiceReference.blockRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.blockResponse1> blockAsync(Agent_s_App.UserServiceReference.blockRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.addUserResponse1 addUser(Agent_s_App.UserServiceReference.addUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.addUserResponse1> addUserAsync(Agent_s_App.UserServiceReference.addUserRequest1 request);
        
        // CODEGEN: Generating message contract since the operation delete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.deleteResponse1 delete(Agent_s_App.UserServiceReference.deleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.deleteResponse1> deleteAsync(Agent_s_App.UserServiceReference.deleteRequest1 request);
        
        // CODEGEN: Generating message contract since the operation updateUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.updateUserResponse1 updateUser(Agent_s_App.UserServiceReference.updateUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.updateUserResponse1> updateUserAsync(Agent_s_App.UserServiceReference.updateUserRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUsers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.UserServiceReference.getUsersResponse getUsers(Agent_s_App.UserServiceReference.getUsersRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.getUsersResponse> getUsersAsync(Agent_s_App.UserServiceReference.getUsersRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class unblockRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public partial class comment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentOfCommentField;
        
        private bool approvedCommentField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string contentOfComment {
            get {
                return this.contentOfCommentField;
            }
            set {
                this.contentOfCommentField = value;
                this.RaisePropertyChanged("contentOfComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool approvedComment {
            get {
                return this.approvedCommentField;
            }
            set {
                this.approvedCommentField = value;
                this.RaisePropertyChanged("approvedComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public partial class accommodation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string nameField;
        
        private string categoryField;
        
        private Address addressField;
        
        private accommodationType accommodationTypeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public accommodationType AccommodationType {
            get {
                return this.accommodationTypeField;
            }
            set {
                this.accommodationTypeField = value;
                this.RaisePropertyChanged("AccommodationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string cityField;
        
        private int postal_codeField;
        
        private string streetField;
        
        private string numberField;
        
        private string apartment_numberField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                this.postal_codeField = value;
                this.RaisePropertyChanged("Postal_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Apartment_number {
            get {
                return this.apartment_numberField;
            }
            set {
                this.apartment_numberField = value;
                this.RaisePropertyChanged("Apartment_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public enum accommodationType {
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        MOTEL,
        
        /// <remarks/>
        BED_AND_BREAKFAST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string lastnameField;
        
        private string emailField;
        
        private string usernameField;
        
        private string passwordField;
        
        private long idField;
        
        private bool enabledField;
        
        private bool deletedField;
        
        private string roleField;
        
        private Address addressField;
        
        private long bussines_registration_numberField;
        
        private bool blockedField;
        
        private accommodation accommodationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("Lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long Bussines_registration_number {
            get {
                return this.bussines_registration_numberField;
            }
            set {
                this.bussines_registration_numberField = value;
                this.RaisePropertyChanged("Bussines_registration_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
                this.RaisePropertyChanged("Blocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public accommodation Accommodation {
            get {
                return this.accommodationField;
            }
            set {
                this.accommodationField = value;
                this.RaisePropertyChanged("Accommodation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/mojuser")]
    public partial class LoginDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("role");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class unblockResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class unblockRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.unblockRequest unblockRequest;
        
        public unblockRequest1() {
        }
        
        public unblockRequest1(Agent_s_App.UserServiceReference.unblockRequest unblockRequest) {
            this.unblockRequest = unblockRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class unblockResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.unblockResponse unblockResponse;
        
        public unblockResponse1() {
        }
        
        public unblockResponse1(Agent_s_App.UserServiceReference.unblockResponse unblockResponse) {
            this.unblockResponse = unblockResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class loginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LoginDTO loginDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LoginDTO loginDTO {
            get {
                return this.loginDTOField;
            }
            set {
                this.loginDTOField = value;
                this.RaisePropertyChanged("loginDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class loginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.loginRequest loginRequest;
        
        public loginRequest1() {
        }
        
        public loginRequest1(Agent_s_App.UserServiceReference.loginRequest loginRequest) {
            this.loginRequest = loginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.loginResponse loginResponse;
        
        public loginResponse1() {
        }
        
        public loginResponse1(Agent_s_App.UserServiceReference.loginResponse loginResponse) {
            this.loginResponse = loginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class addAccommodationToUserRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationIdField;
        
        private long userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long AccommodationId {
            get {
                return this.accommodationIdField;
            }
            set {
                this.accommodationIdField = value;
                this.RaisePropertyChanged("AccommodationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class addAccommodationToUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public user User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationToUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.addAccommodationToUserRequest addAccommodationToUserRequest;
        
        public addAccommodationToUserRequest1() {
        }
        
        public addAccommodationToUserRequest1(Agent_s_App.UserServiceReference.addAccommodationToUserRequest addAccommodationToUserRequest) {
            this.addAccommodationToUserRequest = addAccommodationToUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationToUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.addAccommodationToUserResponse addAccommodationToUserResponse;
        
        public addAccommodationToUserResponse1() {
        }
        
        public addAccommodationToUserResponse1(Agent_s_App.UserServiceReference.addAccommodationToUserResponse addAccommodationToUserResponse) {
            this.addAccommodationToUserResponse = addAccommodationToUserResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class activateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class activateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.activateRequest activateRequest;
        
        public activateRequest1() {
        }
        
        public activateRequest1(Agent_s_App.UserServiceReference.activateRequest activateRequest) {
            this.activateRequest = activateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.activateResponse activateResponse;
        
        public activateResponse1() {
        }
        
        public activateResponse1(Agent_s_App.UserServiceReference.activateResponse activateResponse) {
            this.activateResponse = activateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class getUserCommentsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserCommentsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.getUserCommentsRequest getUserCommentsRequest;
        
        public getUserCommentsRequest1() {
        }
        
        public getUserCommentsRequest1(Agent_s_App.UserServiceReference.getUserCommentsRequest getUserCommentsRequest) {
            this.getUserCommentsRequest = getUserCommentsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserCommentsResponse", Namespace="http://www.projectXml.com/mojuser", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comments", IsNullable=false)]
        public Agent_s_App.UserServiceReference.comment[] getUserCommentsResponse1;
        
        public getUserCommentsResponse() {
        }
        
        public getUserCommentsResponse(Agent_s_App.UserServiceReference.comment[] getUserCommentsResponse1) {
            this.getUserCommentsResponse1 = getUserCommentsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class blockRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class blockResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class blockRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.blockRequest blockRequest;
        
        public blockRequest1() {
        }
        
        public blockRequest1(Agent_s_App.UserServiceReference.blockRequest blockRequest) {
            this.blockRequest = blockRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class blockResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.blockResponse blockResponse;
        
        public blockResponse1() {
        }
        
        public blockResponse1(Agent_s_App.UserServiceReference.blockResponse blockResponse) {
            this.blockResponse = blockResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class addUserRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class addUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.addUserRequest addUserRequest;
        
        public addUserRequest1() {
        }
        
        public addUserRequest1(Agent_s_App.UserServiceReference.addUserRequest addUserRequest) {
            this.addUserRequest = addUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.addUserResponse addUserResponse;
        
        public addUserResponse1() {
        }
        
        public addUserResponse1(Agent_s_App.UserServiceReference.addUserResponse addUserResponse) {
            this.addUserResponse = addUserResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class deleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class deleteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.deleteRequest deleteRequest;
        
        public deleteRequest1() {
        }
        
        public deleteRequest1(Agent_s_App.UserServiceReference.deleteRequest deleteRequest) {
            this.deleteRequest = deleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.deleteResponse deleteResponse;
        
        public deleteResponse1() {
        }
        
        public deleteResponse1(Agent_s_App.UserServiceReference.deleteResponse deleteResponse) {
            this.deleteResponse = deleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class updateUserRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private user userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class updateUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.updateUserRequest updateUserRequest;
        
        public updateUserRequest1() {
        }
        
        public updateUserRequest1(Agent_s_App.UserServiceReference.updateUserRequest updateUserRequest) {
            this.updateUserRequest = updateUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.updateUserResponse updateUserResponse;
        
        public updateUserResponse1() {
        }
        
        public updateUserResponse1(Agent_s_App.UserServiceReference.updateUserResponse updateUserResponse) {
            this.updateUserResponse = updateUserResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/mojuser")]
    public partial class getUsersRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/mojuser", Order=0)]
        public Agent_s_App.UserServiceReference.getUsersRequest getUsersRequest;
        
        public getUsersRequest1() {
        }
        
        public getUsersRequest1(Agent_s_App.UserServiceReference.getUsersRequest getUsersRequest) {
            this.getUsersRequest = getUsersRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsersResponse", Namespace="http://www.projectXml.com/mojuser", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Agent_s_App.UserServiceReference.user[] getUsersResponse1;
        
        public getUsersResponse() {
        }
        
        public getUsersResponse(Agent_s_App.UserServiceReference.user[] getUsersResponse1) {
            this.getUsersResponse1 = getUsersResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MojuserPortChannel : Agent_s_App.UserServiceReference.MojuserPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MojuserPortClient : System.ServiceModel.ClientBase<Agent_s_App.UserServiceReference.MojuserPort>, Agent_s_App.UserServiceReference.MojuserPort {
        
        public MojuserPortClient() {
        }
        
        public MojuserPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MojuserPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MojuserPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MojuserPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.unblockResponse1 Agent_s_App.UserServiceReference.MojuserPort.unblock(Agent_s_App.UserServiceReference.unblockRequest1 request) {
            return base.Channel.unblock(request);
        }
        
        public Agent_s_App.UserServiceReference.unblockResponse unblock(Agent_s_App.UserServiceReference.unblockRequest unblockRequest) {
            Agent_s_App.UserServiceReference.unblockRequest1 inValue = new Agent_s_App.UserServiceReference.unblockRequest1();
            inValue.unblockRequest = unblockRequest;
            Agent_s_App.UserServiceReference.unblockResponse1 retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).unblock(inValue);
            return retVal.unblockResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.unblockResponse1> Agent_s_App.UserServiceReference.MojuserPort.unblockAsync(Agent_s_App.UserServiceReference.unblockRequest1 request) {
            return base.Channel.unblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.unblockResponse1> unblockAsync(Agent_s_App.UserServiceReference.unblockRequest unblockRequest) {
            Agent_s_App.UserServiceReference.unblockRequest1 inValue = new Agent_s_App.UserServiceReference.unblockRequest1();
            inValue.unblockRequest = unblockRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).unblockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.loginResponse1 Agent_s_App.UserServiceReference.MojuserPort.login(Agent_s_App.UserServiceReference.loginRequest1 request) {
            return base.Channel.login(request);
        }
        
        public Agent_s_App.UserServiceReference.loginResponse login(Agent_s_App.UserServiceReference.loginRequest loginRequest) {
            Agent_s_App.UserServiceReference.loginRequest1 inValue = new Agent_s_App.UserServiceReference.loginRequest1();
            inValue.loginRequest = loginRequest;
            Agent_s_App.UserServiceReference.loginResponse1 retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).login(inValue);
            return retVal.loginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.loginResponse1> Agent_s_App.UserServiceReference.MojuserPort.loginAsync(Agent_s_App.UserServiceReference.loginRequest1 request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.loginResponse1> loginAsync(Agent_s_App.UserServiceReference.loginRequest loginRequest) {
            Agent_s_App.UserServiceReference.loginRequest1 inValue = new Agent_s_App.UserServiceReference.loginRequest1();
            inValue.loginRequest = loginRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.addAccommodationToUserResponse1 Agent_s_App.UserServiceReference.MojuserPort.addAccommodationToUser(Agent_s_App.UserServiceReference.addAccommodationToUserRequest1 request) {
            return base.Channel.addAccommodationToUser(request);
        }
        
        public Agent_s_App.UserServiceReference.addAccommodationToUserResponse addAccommodationToUser(Agent_s_App.UserServiceReference.addAccommodationToUserRequest addAccommodationToUserRequest) {
            Agent_s_App.UserServiceReference.addAccommodationToUserRequest1 inValue = new Agent_s_App.UserServiceReference.addAccommodationToUserRequest1();
            inValue.addAccommodationToUserRequest = addAccommodationToUserRequest;
            Agent_s_App.UserServiceReference.addAccommodationToUserResponse1 retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).addAccommodationToUser(inValue);
            return retVal.addAccommodationToUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.addAccommodationToUserResponse1> Agent_s_App.UserServiceReference.MojuserPort.addAccommodationToUserAsync(Agent_s_App.UserServiceReference.addAccommodationToUserRequest1 request) {
            return base.Channel.addAccommodationToUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.addAccommodationToUserResponse1> addAccommodationToUserAsync(Agent_s_App.UserServiceReference.addAccommodationToUserRequest addAccommodationToUserRequest) {
            Agent_s_App.UserServiceReference.addAccommodationToUserRequest1 inValue = new Agent_s_App.UserServiceReference.addAccommodationToUserRequest1();
            inValue.addAccommodationToUserRequest = addAccommodationToUserRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).addAccommodationToUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.activateResponse1 Agent_s_App.UserServiceReference.MojuserPort.activate(Agent_s_App.UserServiceReference.activateRequest1 request) {
            return base.Channel.activate(request);
        }
        
        public Agent_s_App.UserServiceReference.activateResponse activate(Agent_s_App.UserServiceReference.activateRequest activateRequest) {
            Agent_s_App.UserServiceReference.activateRequest1 inValue = new Agent_s_App.UserServiceReference.activateRequest1();
            inValue.activateRequest = activateRequest;
            Agent_s_App.UserServiceReference.activateResponse1 retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).activate(inValue);
            return retVal.activateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.activateResponse1> Agent_s_App.UserServiceReference.MojuserPort.activateAsync(Agent_s_App.UserServiceReference.activateRequest1 request) {
            return base.Channel.activateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.activateResponse1> activateAsync(Agent_s_App.UserServiceReference.activateRequest activateRequest) {
            Agent_s_App.UserServiceReference.activateRequest1 inValue = new Agent_s_App.UserServiceReference.activateRequest1();
            inValue.activateRequest = activateRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).activateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.getUserCommentsResponse Agent_s_App.UserServiceReference.MojuserPort.getUserComments(Agent_s_App.UserServiceReference.getUserCommentsRequest1 request) {
            return base.Channel.getUserComments(request);
        }
        
        public Agent_s_App.UserServiceReference.comment[] getUserComments(Agent_s_App.UserServiceReference.getUserCommentsRequest getUserCommentsRequest) {
            Agent_s_App.UserServiceReference.getUserCommentsRequest1 inValue = new Agent_s_App.UserServiceReference.getUserCommentsRequest1();
            inValue.getUserCommentsRequest = getUserCommentsRequest;
            Agent_s_App.UserServiceReference.getUserCommentsResponse retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).getUserComments(inValue);
            return retVal.getUserCommentsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.getUserCommentsResponse> Agent_s_App.UserServiceReference.MojuserPort.getUserCommentsAsync(Agent_s_App.UserServiceReference.getUserCommentsRequest1 request) {
            return base.Channel.getUserCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.getUserCommentsResponse> getUserCommentsAsync(Agent_s_App.UserServiceReference.getUserCommentsRequest getUserCommentsRequest) {
            Agent_s_App.UserServiceReference.getUserCommentsRequest1 inValue = new Agent_s_App.UserServiceReference.getUserCommentsRequest1();
            inValue.getUserCommentsRequest = getUserCommentsRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).getUserCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.blockResponse1 Agent_s_App.UserServiceReference.MojuserPort.block(Agent_s_App.UserServiceReference.blockRequest1 request) {
            return base.Channel.block(request);
        }
        
        public Agent_s_App.UserServiceReference.blockResponse block(Agent_s_App.UserServiceReference.blockRequest blockRequest) {
            Agent_s_App.UserServiceReference.blockRequest1 inValue = new Agent_s_App.UserServiceReference.blockRequest1();
            inValue.blockRequest = blockRequest;
            Agent_s_App.UserServiceReference.blockResponse1 retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).block(inValue);
            return retVal.blockResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.blockResponse1> Agent_s_App.UserServiceReference.MojuserPort.blockAsync(Agent_s_App.UserServiceReference.blockRequest1 request) {
            return base.Channel.blockAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.blockResponse1> blockAsync(Agent_s_App.UserServiceReference.blockRequest blockRequest) {
            Agent_s_App.UserServiceReference.blockRequest1 inValue = new Agent_s_App.UserServiceReference.blockRequest1();
            inValue.blockRequest = blockRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).blockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.addUserResponse1 Agent_s_App.UserServiceReference.MojuserPort.addUser(Agent_s_App.UserServiceReference.addUserRequest1 request) {
            return base.Channel.addUser(request);
        }
        
        public Agent_s_App.UserServiceReference.addUserResponse addUser(Agent_s_App.UserServiceReference.addUserRequest addUserRequest) {
            Agent_s_App.UserServiceReference.addUserRequest1 inValue = new Agent_s_App.UserServiceReference.addUserRequest1();
            inValue.addUserRequest = addUserRequest;
            Agent_s_App.UserServiceReference.addUserResponse1 retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).addUser(inValue);
            return retVal.addUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.addUserResponse1> Agent_s_App.UserServiceReference.MojuserPort.addUserAsync(Agent_s_App.UserServiceReference.addUserRequest1 request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.addUserResponse1> addUserAsync(Agent_s_App.UserServiceReference.addUserRequest addUserRequest) {
            Agent_s_App.UserServiceReference.addUserRequest1 inValue = new Agent_s_App.UserServiceReference.addUserRequest1();
            inValue.addUserRequest = addUserRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.deleteResponse1 Agent_s_App.UserServiceReference.MojuserPort.delete(Agent_s_App.UserServiceReference.deleteRequest1 request) {
            return base.Channel.delete(request);
        }
        
        public Agent_s_App.UserServiceReference.deleteResponse delete(Agent_s_App.UserServiceReference.deleteRequest deleteRequest) {
            Agent_s_App.UserServiceReference.deleteRequest1 inValue = new Agent_s_App.UserServiceReference.deleteRequest1();
            inValue.deleteRequest = deleteRequest;
            Agent_s_App.UserServiceReference.deleteResponse1 retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).delete(inValue);
            return retVal.deleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.deleteResponse1> Agent_s_App.UserServiceReference.MojuserPort.deleteAsync(Agent_s_App.UserServiceReference.deleteRequest1 request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.deleteResponse1> deleteAsync(Agent_s_App.UserServiceReference.deleteRequest deleteRequest) {
            Agent_s_App.UserServiceReference.deleteRequest1 inValue = new Agent_s_App.UserServiceReference.deleteRequest1();
            inValue.deleteRequest = deleteRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.updateUserResponse1 Agent_s_App.UserServiceReference.MojuserPort.updateUser(Agent_s_App.UserServiceReference.updateUserRequest1 request) {
            return base.Channel.updateUser(request);
        }
        
        public Agent_s_App.UserServiceReference.updateUserResponse updateUser(Agent_s_App.UserServiceReference.updateUserRequest updateUserRequest) {
            Agent_s_App.UserServiceReference.updateUserRequest1 inValue = new Agent_s_App.UserServiceReference.updateUserRequest1();
            inValue.updateUserRequest = updateUserRequest;
            Agent_s_App.UserServiceReference.updateUserResponse1 retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).updateUser(inValue);
            return retVal.updateUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.updateUserResponse1> Agent_s_App.UserServiceReference.MojuserPort.updateUserAsync(Agent_s_App.UserServiceReference.updateUserRequest1 request) {
            return base.Channel.updateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.updateUserResponse1> updateUserAsync(Agent_s_App.UserServiceReference.updateUserRequest updateUserRequest) {
            Agent_s_App.UserServiceReference.updateUserRequest1 inValue = new Agent_s_App.UserServiceReference.updateUserRequest1();
            inValue.updateUserRequest = updateUserRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).updateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.UserServiceReference.getUsersResponse Agent_s_App.UserServiceReference.MojuserPort.getUsers(Agent_s_App.UserServiceReference.getUsersRequest1 request) {
            return base.Channel.getUsers(request);
        }
        
        public Agent_s_App.UserServiceReference.user[] getUsers(Agent_s_App.UserServiceReference.getUsersRequest getUsersRequest) {
            Agent_s_App.UserServiceReference.getUsersRequest1 inValue = new Agent_s_App.UserServiceReference.getUsersRequest1();
            inValue.getUsersRequest = getUsersRequest;
            Agent_s_App.UserServiceReference.getUsersResponse retVal = ((Agent_s_App.UserServiceReference.MojuserPort)(this)).getUsers(inValue);
            return retVal.getUsersResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.getUsersResponse> Agent_s_App.UserServiceReference.MojuserPort.getUsersAsync(Agent_s_App.UserServiceReference.getUsersRequest1 request) {
            return base.Channel.getUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.UserServiceReference.getUsersResponse> getUsersAsync(Agent_s_App.UserServiceReference.getUsersRequest getUsersRequest) {
            Agent_s_App.UserServiceReference.getUsersRequest1 inValue = new Agent_s_App.UserServiceReference.getUsersRequest1();
            inValue.getUsersRequest = getUsersRequest;
            return ((Agent_s_App.UserServiceReference.MojuserPort)(this)).getUsersAsync(inValue);
        }
    }
}
