//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_s_App.AddressServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.projectXml.com/address", ConfigurationName="AddressServiceReference.AddressPort")]
    public interface AddressPort {
        
        // CODEGEN: Generating message contract since the operation addAddress is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AddressServiceReference.addAddressResponse1 addAddress(Agent_s_App.AddressServiceReference.addAddressRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AddressServiceReference.addAddressResponse1> addAddressAsync(Agent_s_App.AddressServiceReference.addAddressRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getAddress is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AddressServiceReference.getAddressResponse1 getAddress(Agent_s_App.AddressServiceReference.getAddressRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AddressServiceReference.getAddressResponse1> getAddressAsync(Agent_s_App.AddressServiceReference.getAddressRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/address")]
    public partial class addAddressRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private address addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/address")]
    public partial class address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string cityField;
        
        private int postal_codeField;
        
        private string streetField;
        
        private string numberField;
        
        private string apartment_numberField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                this.postal_codeField = value;
                this.RaisePropertyChanged("Postal_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Apartment_number {
            get {
                return this.apartment_numberField;
            }
            set {
                this.apartment_numberField = value;
                this.RaisePropertyChanged("Apartment_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/address")]
    public partial class addAddressResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAddressRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/address", Order=0)]
        public Agent_s_App.AddressServiceReference.addAddressRequest addAddressRequest;
        
        public addAddressRequest1() {
        }
        
        public addAddressRequest1(Agent_s_App.AddressServiceReference.addAddressRequest addAddressRequest) {
            this.addAddressRequest = addAddressRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAddressResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/address", Order=0)]
        public Agent_s_App.AddressServiceReference.addAddressResponse addAddressResponse;
        
        public addAddressResponse1() {
        }
        
        public addAddressResponse1(Agent_s_App.AddressServiceReference.addAddressResponse addAddressResponse) {
            this.addAddressResponse = addAddressResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/address")]
    public partial class getAddressRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/address")]
    public partial class getAddressResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private address addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/address", Order=0)]
        public Agent_s_App.AddressServiceReference.getAddressRequest getAddressRequest;
        
        public getAddressRequest1() {
        }
        
        public getAddressRequest1(Agent_s_App.AddressServiceReference.getAddressRequest getAddressRequest) {
            this.getAddressRequest = getAddressRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAddressResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/address", Order=0)]
        public Agent_s_App.AddressServiceReference.getAddressResponse getAddressResponse;
        
        public getAddressResponse1() {
        }
        
        public getAddressResponse1(Agent_s_App.AddressServiceReference.getAddressResponse getAddressResponse) {
            this.getAddressResponse = getAddressResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddressPortChannel : Agent_s_App.AddressServiceReference.AddressPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressPortClient : System.ServiceModel.ClientBase<Agent_s_App.AddressServiceReference.AddressPort>, Agent_s_App.AddressServiceReference.AddressPort {
        
        public AddressPortClient() {
        }
        
        public AddressPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AddressServiceReference.addAddressResponse1 Agent_s_App.AddressServiceReference.AddressPort.addAddress(Agent_s_App.AddressServiceReference.addAddressRequest1 request) {
            return base.Channel.addAddress(request);
        }
        
        public Agent_s_App.AddressServiceReference.addAddressResponse addAddress(Agent_s_App.AddressServiceReference.addAddressRequest addAddressRequest) {
            Agent_s_App.AddressServiceReference.addAddressRequest1 inValue = new Agent_s_App.AddressServiceReference.addAddressRequest1();
            inValue.addAddressRequest = addAddressRequest;
            Agent_s_App.AddressServiceReference.addAddressResponse1 retVal = ((Agent_s_App.AddressServiceReference.AddressPort)(this)).addAddress(inValue);
            return retVal.addAddressResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AddressServiceReference.addAddressResponse1> Agent_s_App.AddressServiceReference.AddressPort.addAddressAsync(Agent_s_App.AddressServiceReference.addAddressRequest1 request) {
            return base.Channel.addAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AddressServiceReference.addAddressResponse1> addAddressAsync(Agent_s_App.AddressServiceReference.addAddressRequest addAddressRequest) {
            Agent_s_App.AddressServiceReference.addAddressRequest1 inValue = new Agent_s_App.AddressServiceReference.addAddressRequest1();
            inValue.addAddressRequest = addAddressRequest;
            return ((Agent_s_App.AddressServiceReference.AddressPort)(this)).addAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AddressServiceReference.getAddressResponse1 Agent_s_App.AddressServiceReference.AddressPort.getAddress(Agent_s_App.AddressServiceReference.getAddressRequest1 request) {
            return base.Channel.getAddress(request);
        }
        
        public Agent_s_App.AddressServiceReference.getAddressResponse getAddress(Agent_s_App.AddressServiceReference.getAddressRequest getAddressRequest) {
            Agent_s_App.AddressServiceReference.getAddressRequest1 inValue = new Agent_s_App.AddressServiceReference.getAddressRequest1();
            inValue.getAddressRequest = getAddressRequest;
            Agent_s_App.AddressServiceReference.getAddressResponse1 retVal = ((Agent_s_App.AddressServiceReference.AddressPort)(this)).getAddress(inValue);
            return retVal.getAddressResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AddressServiceReference.getAddressResponse1> Agent_s_App.AddressServiceReference.AddressPort.getAddressAsync(Agent_s_App.AddressServiceReference.getAddressRequest1 request) {
            return base.Channel.getAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AddressServiceReference.getAddressResponse1> getAddressAsync(Agent_s_App.AddressServiceReference.getAddressRequest getAddressRequest) {
            Agent_s_App.AddressServiceReference.getAddressRequest1 inValue = new Agent_s_App.AddressServiceReference.getAddressRequest1();
            inValue.getAddressRequest = getAddressRequest;
            return ((Agent_s_App.AddressServiceReference.AddressPort)(this)).getAddressAsync(inValue);
        }
    }
}
