//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_s_App.AccommodationServiceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.projectXml.com/service", ConfigurationName="AccommodationServiceServiceReference.ServicePort")]
    public interface ServicePort {
        
        // CODEGEN: Generating message contract since the operation addAccommodationService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceResponse1 addAccommodationService(Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceResponse1> addAccommodationServiceAsync(Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getAccommodationServices is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesResponse1 getAccommodationServices(Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesResponse1> getAccommodationServicesAsync(Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation removeAccommodationService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void removeAccommodationService(Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task removeAccommodationServiceAsync(Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation removeService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void removeService(Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task removeServiceAsync(Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getServices is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AccommodationServiceServiceReference.getServicesResponse1 getServices(Agent_s_App.AccommodationServiceServiceReference.getServicesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.getServicesResponse1> getServicesAsync(Agent_s_App.AccommodationServiceServiceReference.getServicesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AccommodationServiceServiceReference.getServiceResponse1 getService(Agent_s_App.AccommodationServiceServiceReference.getServiceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.getServiceResponse1> getServiceAsync(Agent_s_App.AccommodationServiceServiceReference.getServiceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AccommodationServiceServiceReference.addServiceResponse1 addService(Agent_s_App.AccommodationServiceServiceReference.addServiceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.addServiceResponse1> addServiceAsync(Agent_s_App.AccommodationServiceServiceReference.addServiceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation updateService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updateService(Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task updateServiceAsync(Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class addAccommodationServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationIdField;
        
        private long serviceIdField;
        
        private service serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationId {
            get {
                return this.accommodationIdField;
            }
            set {
                this.accommodationIdField = value;
                this.RaisePropertyChanged("accommodationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public service service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("service");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/service")]
    public partial class service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class addAccommodationServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private service serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public service service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("service");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationServiceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest addAccommodationServiceRequest;
        
        public addAccommodationServiceRequest1() {
        }
        
        public addAccommodationServiceRequest1(Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest addAccommodationServiceRequest) {
            this.addAccommodationServiceRequest = addAccommodationServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationServiceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceResponse addAccommodationServiceResponse;
        
        public addAccommodationServiceResponse1() {
        }
        
        public addAccommodationServiceResponse1(Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceResponse addAccommodationServiceResponse) {
            this.addAccommodationServiceResponse = addAccommodationServiceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class getAccommodationServicesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationId {
            get {
                return this.accommodationIdField;
            }
            set {
                this.accommodationIdField = value;
                this.RaisePropertyChanged("accommodationId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class getAccommodationServicesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private service[] servicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Services", IsNullable=false)]
        public service[] services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
                this.RaisePropertyChanged("services");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationServicesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest getAccommodationServicesRequest;
        
        public getAccommodationServicesRequest1() {
        }
        
        public getAccommodationServicesRequest1(Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest getAccommodationServicesRequest) {
            this.getAccommodationServicesRequest = getAccommodationServicesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationServicesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesResponse getAccommodationServicesResponse;
        
        public getAccommodationServicesResponse1() {
        }
        
        public getAccommodationServicesResponse1(Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesResponse getAccommodationServicesResponse) {
            this.getAccommodationServicesResponse = getAccommodationServicesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class removeAccommodationServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accommodationIdField;
        
        private long accommodationServiceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long accommodationId {
            get {
                return this.accommodationIdField;
            }
            set {
                this.accommodationIdField = value;
                this.RaisePropertyChanged("accommodationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long accommodationServiceId {
            get {
                return this.accommodationServiceIdField;
            }
            set {
                this.accommodationServiceIdField = value;
                this.RaisePropertyChanged("accommodationServiceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeAccommodationServiceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest removeAccommodationServiceRequest;
        
        public removeAccommodationServiceRequest1() {
        }
        
        public removeAccommodationServiceRequest1(Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest removeAccommodationServiceRequest) {
            this.removeAccommodationServiceRequest = removeAccommodationServiceRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class removeServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long serviceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeServiceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest removeServiceRequest;
        
        public removeServiceRequest1() {
        }
        
        public removeServiceRequest1(Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest removeServiceRequest) {
            this.removeServiceRequest = removeServiceRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class getServicesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class getServicesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private service[] servicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Services", IsNullable=false)]
        public service[] services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
                this.RaisePropertyChanged("services");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServicesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.getServicesRequest getServicesRequest;
        
        public getServicesRequest1() {
        }
        
        public getServicesRequest1(Agent_s_App.AccommodationServiceServiceReference.getServicesRequest getServicesRequest) {
            this.getServicesRequest = getServicesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServicesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.getServicesResponse getServicesResponse;
        
        public getServicesResponse1() {
        }
        
        public getServicesResponse1(Agent_s_App.AccommodationServiceServiceReference.getServicesResponse getServicesResponse) {
            this.getServicesResponse = getServicesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class getServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long serviceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class getServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private service serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public service service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("service");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.getServiceRequest getServiceRequest;
        
        public getServiceRequest1() {
        }
        
        public getServiceRequest1(Agent_s_App.AccommodationServiceServiceReference.getServiceRequest getServiceRequest) {
            this.getServiceRequest = getServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.getServiceResponse getServiceResponse;
        
        public getServiceResponse1() {
        }
        
        public getServiceResponse1(Agent_s_App.AccommodationServiceServiceReference.getServiceResponse getServiceResponse) {
            this.getServiceResponse = getServiceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class addServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private service serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public service service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("service");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class addServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private service serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public service service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("service");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addServiceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.addServiceRequest addServiceRequest;
        
        public addServiceRequest1() {
        }
        
        public addServiceRequest1(Agent_s_App.AccommodationServiceServiceReference.addServiceRequest addServiceRequest) {
            this.addServiceRequest = addServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addServiceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.addServiceResponse addServiceResponse;
        
        public addServiceResponse1() {
        }
        
        public addServiceResponse1(Agent_s_App.AccommodationServiceServiceReference.addServiceResponse addServiceResponse) {
            this.addServiceResponse = addServiceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/service")]
    public partial class updateServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private service serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public service service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("service");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateServiceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/service", Order=0)]
        public Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest updateServiceRequest;
        
        public updateServiceRequest1() {
        }
        
        public updateServiceRequest1(Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest updateServiceRequest) {
            this.updateServiceRequest = updateServiceRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicePortChannel : Agent_s_App.AccommodationServiceServiceReference.ServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePortClient : System.ServiceModel.ClientBase<Agent_s_App.AccommodationServiceServiceReference.ServicePort>, Agent_s_App.AccommodationServiceServiceReference.ServicePort {
        
        public ServicePortClient() {
        }
        
        public ServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceResponse1 Agent_s_App.AccommodationServiceServiceReference.ServicePort.addAccommodationService(Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest1 request) {
            return base.Channel.addAccommodationService(request);
        }
        
        public Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceResponse addAccommodationService(Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest addAccommodationServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest1();
            inValue.addAccommodationServiceRequest = addAccommodationServiceRequest;
            Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceResponse1 retVal = ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).addAccommodationService(inValue);
            return retVal.addAccommodationServiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceResponse1> Agent_s_App.AccommodationServiceServiceReference.ServicePort.addAccommodationServiceAsync(Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest1 request) {
            return base.Channel.addAccommodationServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceResponse1> addAccommodationServiceAsync(Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest addAccommodationServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.addAccommodationServiceRequest1();
            inValue.addAccommodationServiceRequest = addAccommodationServiceRequest;
            return ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).addAccommodationServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesResponse1 Agent_s_App.AccommodationServiceServiceReference.ServicePort.getAccommodationServices(Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest1 request) {
            return base.Channel.getAccommodationServices(request);
        }
        
        public Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesResponse getAccommodationServices(Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest getAccommodationServicesRequest) {
            Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest1();
            inValue.getAccommodationServicesRequest = getAccommodationServicesRequest;
            Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesResponse1 retVal = ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).getAccommodationServices(inValue);
            return retVal.getAccommodationServicesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesResponse1> Agent_s_App.AccommodationServiceServiceReference.ServicePort.getAccommodationServicesAsync(Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest1 request) {
            return base.Channel.getAccommodationServicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesResponse1> getAccommodationServicesAsync(Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest getAccommodationServicesRequest) {
            Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.getAccommodationServicesRequest1();
            inValue.getAccommodationServicesRequest = getAccommodationServicesRequest;
            return ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).getAccommodationServicesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Agent_s_App.AccommodationServiceServiceReference.ServicePort.removeAccommodationService(Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest1 request) {
            base.Channel.removeAccommodationService(request);
        }
        
        public void removeAccommodationService(Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest removeAccommodationServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest1();
            inValue.removeAccommodationServiceRequest = removeAccommodationServiceRequest;
            ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).removeAccommodationService(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Agent_s_App.AccommodationServiceServiceReference.ServicePort.removeAccommodationServiceAsync(Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest1 request) {
            return base.Channel.removeAccommodationServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task removeAccommodationServiceAsync(Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest removeAccommodationServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.removeAccommodationServiceRequest1();
            inValue.removeAccommodationServiceRequest = removeAccommodationServiceRequest;
            return ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).removeAccommodationServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Agent_s_App.AccommodationServiceServiceReference.ServicePort.removeService(Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest1 request) {
            base.Channel.removeService(request);
        }
        
        public void removeService(Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest removeServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest1();
            inValue.removeServiceRequest = removeServiceRequest;
            ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).removeService(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Agent_s_App.AccommodationServiceServiceReference.ServicePort.removeServiceAsync(Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest1 request) {
            return base.Channel.removeServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task removeServiceAsync(Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest removeServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.removeServiceRequest1();
            inValue.removeServiceRequest = removeServiceRequest;
            return ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).removeServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AccommodationServiceServiceReference.getServicesResponse1 Agent_s_App.AccommodationServiceServiceReference.ServicePort.getServices(Agent_s_App.AccommodationServiceServiceReference.getServicesRequest1 request) {
            return base.Channel.getServices(request);
        }
        
        public Agent_s_App.AccommodationServiceServiceReference.getServicesResponse getServices(Agent_s_App.AccommodationServiceServiceReference.getServicesRequest getServicesRequest) {
            Agent_s_App.AccommodationServiceServiceReference.getServicesRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.getServicesRequest1();
            inValue.getServicesRequest = getServicesRequest;
            Agent_s_App.AccommodationServiceServiceReference.getServicesResponse1 retVal = ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).getServices(inValue);
            return retVal.getServicesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.getServicesResponse1> Agent_s_App.AccommodationServiceServiceReference.ServicePort.getServicesAsync(Agent_s_App.AccommodationServiceServiceReference.getServicesRequest1 request) {
            return base.Channel.getServicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.getServicesResponse1> getServicesAsync(Agent_s_App.AccommodationServiceServiceReference.getServicesRequest getServicesRequest) {
            Agent_s_App.AccommodationServiceServiceReference.getServicesRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.getServicesRequest1();
            inValue.getServicesRequest = getServicesRequest;
            return ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).getServicesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AccommodationServiceServiceReference.getServiceResponse1 Agent_s_App.AccommodationServiceServiceReference.ServicePort.getService(Agent_s_App.AccommodationServiceServiceReference.getServiceRequest1 request) {
            return base.Channel.getService(request);
        }
        
        public Agent_s_App.AccommodationServiceServiceReference.getServiceResponse getService(Agent_s_App.AccommodationServiceServiceReference.getServiceRequest getServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.getServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.getServiceRequest1();
            inValue.getServiceRequest = getServiceRequest;
            Agent_s_App.AccommodationServiceServiceReference.getServiceResponse1 retVal = ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).getService(inValue);
            return retVal.getServiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.getServiceResponse1> Agent_s_App.AccommodationServiceServiceReference.ServicePort.getServiceAsync(Agent_s_App.AccommodationServiceServiceReference.getServiceRequest1 request) {
            return base.Channel.getServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.getServiceResponse1> getServiceAsync(Agent_s_App.AccommodationServiceServiceReference.getServiceRequest getServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.getServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.getServiceRequest1();
            inValue.getServiceRequest = getServiceRequest;
            return ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).getServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AccommodationServiceServiceReference.addServiceResponse1 Agent_s_App.AccommodationServiceServiceReference.ServicePort.addService(Agent_s_App.AccommodationServiceServiceReference.addServiceRequest1 request) {
            return base.Channel.addService(request);
        }
        
        public Agent_s_App.AccommodationServiceServiceReference.addServiceResponse addService(Agent_s_App.AccommodationServiceServiceReference.addServiceRequest addServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.addServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.addServiceRequest1();
            inValue.addServiceRequest = addServiceRequest;
            Agent_s_App.AccommodationServiceServiceReference.addServiceResponse1 retVal = ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).addService(inValue);
            return retVal.addServiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.addServiceResponse1> Agent_s_App.AccommodationServiceServiceReference.ServicePort.addServiceAsync(Agent_s_App.AccommodationServiceServiceReference.addServiceRequest1 request) {
            return base.Channel.addServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceServiceReference.addServiceResponse1> addServiceAsync(Agent_s_App.AccommodationServiceServiceReference.addServiceRequest addServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.addServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.addServiceRequest1();
            inValue.addServiceRequest = addServiceRequest;
            return ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).addServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Agent_s_App.AccommodationServiceServiceReference.ServicePort.updateService(Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest1 request) {
            base.Channel.updateService(request);
        }
        
        public void updateService(Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest updateServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest1();
            inValue.updateServiceRequest = updateServiceRequest;
            ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).updateService(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Agent_s_App.AccommodationServiceServiceReference.ServicePort.updateServiceAsync(Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest1 request) {
            return base.Channel.updateServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task updateServiceAsync(Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest updateServiceRequest) {
            Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest1 inValue = new Agent_s_App.AccommodationServiceServiceReference.updateServiceRequest1();
            inValue.updateServiceRequest = updateServiceRequest;
            return ((Agent_s_App.AccommodationServiceServiceReference.ServicePort)(this)).updateServiceAsync(inValue);
        }
    }
}
