//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_s_App.AccommodationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.projectXml.com/accommodation", ConfigurationName="AccommodationServiceReference.AccommodationPort")]
    public interface AccommodationPort {
        
        // CODEGEN: Generating message contract since the operation updateAccommodation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updateAccommodation(Agent_s_App.AccommodationServiceReference.updateAccommodationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task updateAccommodationAsync(Agent_s_App.AccommodationServiceReference.updateAccommodationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getAccommodations is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AccommodationServiceReference.getAccommodationsResponse1 getAccommodations(Agent_s_App.AccommodationServiceReference.getAccommodationsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.getAccommodationsResponse1> getAccommodationsAsync(Agent_s_App.AccommodationServiceReference.getAccommodationsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getAccommodation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AccommodationServiceReference.getAccommodationResponse1 getAccommodation(Agent_s_App.AccommodationServiceReference.getAccommodationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.getAccommodationResponse1> getAccommodationAsync(Agent_s_App.AccommodationServiceReference.getAccommodationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addAccommodation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AccommodationServiceReference.addAccommodationResponse1 addAccommodation(Agent_s_App.AccommodationServiceReference.addAccommodationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.addAccommodationResponse1> addAccommodationAsync(Agent_s_App.AccommodationServiceReference.addAccommodationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getAccommodationByUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Agent_s_App.AccommodationServiceReference.getAccommodationByUserResponse1 getAccommodationByUser(Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.getAccommodationByUserResponse1> getAccommodationByUserAsync(Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest1 request);
        
        // CODEGEN: Generating message contract since the operation removeAccommodation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void removeAccommodation(Agent_s_App.AccommodationServiceReference.removeAccommodationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task removeAccommodationAsync(Agent_s_App.AccommodationServiceReference.removeAccommodationRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class updateAccommodationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodation accommodationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodation accommodation {
            get {
                return this.accommodationField;
            }
            set {
                this.accommodationField = value;
                this.RaisePropertyChanged("accommodation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/accommodation")]
    public partial class accommodation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string nameField;
        
        private string categoryField;
        
        private Address addressField;
        
        private accommodationType accommodationTypeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public accommodationType AccommodationType {
            get {
                return this.accommodationTypeField;
            }
            set {
                this.accommodationTypeField = value;
                this.RaisePropertyChanged("AccommodationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/accommodation")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string cityField;
        
        private int postal_codeField;
        
        private string streetField;
        
        private string numberField;
        
        private string apartment_numberField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                this.postal_codeField = value;
                this.RaisePropertyChanged("Postal_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Apartment_number {
            get {
                return this.apartment_numberField;
            }
            set {
                this.apartment_numberField = value;
                this.RaisePropertyChanged("Apartment_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.projectXml.com/accommodation")]
    public enum accommodationType {
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        MOTEL,
        
        /// <remarks/>
        BED_AND_BREAKFAST,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAccommodationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.updateAccommodationRequest updateAccommodationRequest;
        
        public updateAccommodationRequest1() {
        }
        
        public updateAccommodationRequest1(Agent_s_App.AccommodationServiceReference.updateAccommodationRequest updateAccommodationRequest) {
            this.updateAccommodationRequest = updateAccommodationRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class getAccommodationsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class getAccommodationsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodation[] accommodationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Accommodations", IsNullable=false)]
        public accommodation[] accommodations {
            get {
                return this.accommodationsField;
            }
            set {
                this.accommodationsField = value;
                this.RaisePropertyChanged("accommodations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.getAccommodationsRequest getAccommodationsRequest;
        
        public getAccommodationsRequest1() {
        }
        
        public getAccommodationsRequest1(Agent_s_App.AccommodationServiceReference.getAccommodationsRequest getAccommodationsRequest) {
            this.getAccommodationsRequest = getAccommodationsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.getAccommodationsResponse getAccommodationsResponse;
        
        public getAccommodationsResponse1() {
        }
        
        public getAccommodationsResponse1(Agent_s_App.AccommodationServiceReference.getAccommodationsResponse getAccommodationsResponse) {
            this.getAccommodationsResponse = getAccommodationsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class getAccommodationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class getAccommodationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodation accommodationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodation accommodation {
            get {
                return this.accommodationField;
            }
            set {
                this.accommodationField = value;
                this.RaisePropertyChanged("accommodation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.getAccommodationRequest getAccommodationRequest;
        
        public getAccommodationRequest1() {
        }
        
        public getAccommodationRequest1(Agent_s_App.AccommodationServiceReference.getAccommodationRequest getAccommodationRequest) {
            this.getAccommodationRequest = getAccommodationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.getAccommodationResponse getAccommodationResponse;
        
        public getAccommodationResponse1() {
        }
        
        public getAccommodationResponse1(Agent_s_App.AccommodationServiceReference.getAccommodationResponse getAccommodationResponse) {
            this.getAccommodationResponse = getAccommodationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class addAccommodationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodation accommodationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodation accommodation {
            get {
                return this.accommodationField;
            }
            set {
                this.accommodationField = value;
                this.RaisePropertyChanged("accommodation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class addAccommodationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodation accommodationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodation accommodation {
            get {
                return this.accommodationField;
            }
            set {
                this.accommodationField = value;
                this.RaisePropertyChanged("accommodation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.addAccommodationRequest addAccommodationRequest;
        
        public addAccommodationRequest1() {
        }
        
        public addAccommodationRequest1(Agent_s_App.AccommodationServiceReference.addAccommodationRequest addAccommodationRequest) {
            this.addAccommodationRequest = addAccommodationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.addAccommodationResponse addAccommodationResponse;
        
        public addAccommodationResponse1() {
        }
        
        public addAccommodationResponse1(Agent_s_App.AccommodationServiceReference.addAccommodationResponse addAccommodationResponse) {
            this.addAccommodationResponse = addAccommodationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class getAccommodationByUserRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class getAccommodationByUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private accommodation accommodationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public accommodation accommodation {
            get {
                return this.accommodationField;
            }
            set {
                this.accommodationField = value;
                this.RaisePropertyChanged("accommodation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationByUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest getAccommodationByUserRequest;
        
        public getAccommodationByUserRequest1() {
        }
        
        public getAccommodationByUserRequest1(Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest getAccommodationByUserRequest) {
            this.getAccommodationByUserRequest = getAccommodationByUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationByUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.getAccommodationByUserResponse getAccommodationByUserResponse;
        
        public getAccommodationByUserResponse1() {
        }
        
        public getAccommodationByUserResponse1(Agent_s_App.AccommodationServiceReference.getAccommodationByUserResponse getAccommodationByUserResponse) {
            this.getAccommodationByUserResponse = getAccommodationByUserResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.projectXml.com/accommodation")]
    public partial class removeAccommodationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeAccommodationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.projectXml.com/accommodation", Order=0)]
        public Agent_s_App.AccommodationServiceReference.removeAccommodationRequest removeAccommodationRequest;
        
        public removeAccommodationRequest1() {
        }
        
        public removeAccommodationRequest1(Agent_s_App.AccommodationServiceReference.removeAccommodationRequest removeAccommodationRequest) {
            this.removeAccommodationRequest = removeAccommodationRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccommodationPortChannel : Agent_s_App.AccommodationServiceReference.AccommodationPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccommodationPortClient : System.ServiceModel.ClientBase<Agent_s_App.AccommodationServiceReference.AccommodationPort>, Agent_s_App.AccommodationServiceReference.AccommodationPort {
        
        public AccommodationPortClient() {
        }
        
        public AccommodationPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccommodationPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccommodationPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccommodationPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Agent_s_App.AccommodationServiceReference.AccommodationPort.updateAccommodation(Agent_s_App.AccommodationServiceReference.updateAccommodationRequest1 request) {
            base.Channel.updateAccommodation(request);
        }
        
        public void updateAccommodation(Agent_s_App.AccommodationServiceReference.updateAccommodationRequest updateAccommodationRequest) {
            Agent_s_App.AccommodationServiceReference.updateAccommodationRequest1 inValue = new Agent_s_App.AccommodationServiceReference.updateAccommodationRequest1();
            inValue.updateAccommodationRequest = updateAccommodationRequest;
            ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).updateAccommodation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Agent_s_App.AccommodationServiceReference.AccommodationPort.updateAccommodationAsync(Agent_s_App.AccommodationServiceReference.updateAccommodationRequest1 request) {
            return base.Channel.updateAccommodationAsync(request);
        }
        
        public System.Threading.Tasks.Task updateAccommodationAsync(Agent_s_App.AccommodationServiceReference.updateAccommodationRequest updateAccommodationRequest) {
            Agent_s_App.AccommodationServiceReference.updateAccommodationRequest1 inValue = new Agent_s_App.AccommodationServiceReference.updateAccommodationRequest1();
            inValue.updateAccommodationRequest = updateAccommodationRequest;
            return ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).updateAccommodationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AccommodationServiceReference.getAccommodationsResponse1 Agent_s_App.AccommodationServiceReference.AccommodationPort.getAccommodations(Agent_s_App.AccommodationServiceReference.getAccommodationsRequest1 request) {
            return base.Channel.getAccommodations(request);
        }
        
        public Agent_s_App.AccommodationServiceReference.getAccommodationsResponse getAccommodations(Agent_s_App.AccommodationServiceReference.getAccommodationsRequest getAccommodationsRequest) {
            Agent_s_App.AccommodationServiceReference.getAccommodationsRequest1 inValue = new Agent_s_App.AccommodationServiceReference.getAccommodationsRequest1();
            inValue.getAccommodationsRequest = getAccommodationsRequest;
            Agent_s_App.AccommodationServiceReference.getAccommodationsResponse1 retVal = ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).getAccommodations(inValue);
            return retVal.getAccommodationsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.getAccommodationsResponse1> Agent_s_App.AccommodationServiceReference.AccommodationPort.getAccommodationsAsync(Agent_s_App.AccommodationServiceReference.getAccommodationsRequest1 request) {
            return base.Channel.getAccommodationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.getAccommodationsResponse1> getAccommodationsAsync(Agent_s_App.AccommodationServiceReference.getAccommodationsRequest getAccommodationsRequest) {
            Agent_s_App.AccommodationServiceReference.getAccommodationsRequest1 inValue = new Agent_s_App.AccommodationServiceReference.getAccommodationsRequest1();
            inValue.getAccommodationsRequest = getAccommodationsRequest;
            return ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).getAccommodationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AccommodationServiceReference.getAccommodationResponse1 Agent_s_App.AccommodationServiceReference.AccommodationPort.getAccommodation(Agent_s_App.AccommodationServiceReference.getAccommodationRequest1 request) {
            return base.Channel.getAccommodation(request);
        }
        
        public Agent_s_App.AccommodationServiceReference.getAccommodationResponse getAccommodation(Agent_s_App.AccommodationServiceReference.getAccommodationRequest getAccommodationRequest) {
            Agent_s_App.AccommodationServiceReference.getAccommodationRequest1 inValue = new Agent_s_App.AccommodationServiceReference.getAccommodationRequest1();
            inValue.getAccommodationRequest = getAccommodationRequest;
            Agent_s_App.AccommodationServiceReference.getAccommodationResponse1 retVal = ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).getAccommodation(inValue);
            return retVal.getAccommodationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.getAccommodationResponse1> Agent_s_App.AccommodationServiceReference.AccommodationPort.getAccommodationAsync(Agent_s_App.AccommodationServiceReference.getAccommodationRequest1 request) {
            return base.Channel.getAccommodationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.getAccommodationResponse1> getAccommodationAsync(Agent_s_App.AccommodationServiceReference.getAccommodationRequest getAccommodationRequest) {
            Agent_s_App.AccommodationServiceReference.getAccommodationRequest1 inValue = new Agent_s_App.AccommodationServiceReference.getAccommodationRequest1();
            inValue.getAccommodationRequest = getAccommodationRequest;
            return ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).getAccommodationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AccommodationServiceReference.addAccommodationResponse1 Agent_s_App.AccommodationServiceReference.AccommodationPort.addAccommodation(Agent_s_App.AccommodationServiceReference.addAccommodationRequest1 request) {
            return base.Channel.addAccommodation(request);
        }
        
        public Agent_s_App.AccommodationServiceReference.addAccommodationResponse addAccommodation(Agent_s_App.AccommodationServiceReference.addAccommodationRequest addAccommodationRequest) {
            Agent_s_App.AccommodationServiceReference.addAccommodationRequest1 inValue = new Agent_s_App.AccommodationServiceReference.addAccommodationRequest1();
            inValue.addAccommodationRequest = addAccommodationRequest;
            Agent_s_App.AccommodationServiceReference.addAccommodationResponse1 retVal = ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).addAccommodation(inValue);
            return retVal.addAccommodationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.addAccommodationResponse1> Agent_s_App.AccommodationServiceReference.AccommodationPort.addAccommodationAsync(Agent_s_App.AccommodationServiceReference.addAccommodationRequest1 request) {
            return base.Channel.addAccommodationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.addAccommodationResponse1> addAccommodationAsync(Agent_s_App.AccommodationServiceReference.addAccommodationRequest addAccommodationRequest) {
            Agent_s_App.AccommodationServiceReference.addAccommodationRequest1 inValue = new Agent_s_App.AccommodationServiceReference.addAccommodationRequest1();
            inValue.addAccommodationRequest = addAccommodationRequest;
            return ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).addAccommodationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agent_s_App.AccommodationServiceReference.getAccommodationByUserResponse1 Agent_s_App.AccommodationServiceReference.AccommodationPort.getAccommodationByUser(Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest1 request) {
            return base.Channel.getAccommodationByUser(request);
        }
        
        public Agent_s_App.AccommodationServiceReference.getAccommodationByUserResponse getAccommodationByUser(Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest getAccommodationByUserRequest) {
            Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest1 inValue = new Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest1();
            inValue.getAccommodationByUserRequest = getAccommodationByUserRequest;
            Agent_s_App.AccommodationServiceReference.getAccommodationByUserResponse1 retVal = ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).getAccommodationByUser(inValue);
            return retVal.getAccommodationByUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.getAccommodationByUserResponse1> Agent_s_App.AccommodationServiceReference.AccommodationPort.getAccommodationByUserAsync(Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest1 request) {
            return base.Channel.getAccommodationByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agent_s_App.AccommodationServiceReference.getAccommodationByUserResponse1> getAccommodationByUserAsync(Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest getAccommodationByUserRequest) {
            Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest1 inValue = new Agent_s_App.AccommodationServiceReference.getAccommodationByUserRequest1();
            inValue.getAccommodationByUserRequest = getAccommodationByUserRequest;
            return ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).getAccommodationByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Agent_s_App.AccommodationServiceReference.AccommodationPort.removeAccommodation(Agent_s_App.AccommodationServiceReference.removeAccommodationRequest1 request) {
            base.Channel.removeAccommodation(request);
        }
        
        public void removeAccommodation(Agent_s_App.AccommodationServiceReference.removeAccommodationRequest removeAccommodationRequest) {
            Agent_s_App.AccommodationServiceReference.removeAccommodationRequest1 inValue = new Agent_s_App.AccommodationServiceReference.removeAccommodationRequest1();
            inValue.removeAccommodationRequest = removeAccommodationRequest;
            ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).removeAccommodation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Agent_s_App.AccommodationServiceReference.AccommodationPort.removeAccommodationAsync(Agent_s_App.AccommodationServiceReference.removeAccommodationRequest1 request) {
            return base.Channel.removeAccommodationAsync(request);
        }
        
        public System.Threading.Tasks.Task removeAccommodationAsync(Agent_s_App.AccommodationServiceReference.removeAccommodationRequest removeAccommodationRequest) {
            Agent_s_App.AccommodationServiceReference.removeAccommodationRequest1 inValue = new Agent_s_App.AccommodationServiceReference.removeAccommodationRequest1();
            inValue.removeAccommodationRequest = removeAccommodationRequest;
            return ((Agent_s_App.AccommodationServiceReference.AccommodationPort)(this)).removeAccommodationAsync(inValue);
        }
    }
}
